### ISSUE TITLE
more BSD compatible

### ISSUE THREAD

**Issue by freejoins** [GROG/ansible-role-sudo#19]
Hi,
I added if few lines to your defaults for better BSD compatible

default/main.yml

```
#Sudoers file
sudo_sudoers: /etc/sudoers

#root group
root_group: root
```

tasks/main.yml
```
- name: Include OS-specific vars
  include_vars: "{{ ansible_os_family }}.yml"
...
    group: "{{ root_group }}"
...
```

vars/FreeBSD.yml

```
sudo_sudoersd_dir: /usr/local/etc/sudoers.d
sudo_sudoers: /usr/local/etc/sudoers
root_group: wheel
```

**Comment by groggemans** [comment]
Hi @freejoins -- Thank you for your issue, would you like to have a go at a PR yourself?

**Comment by groggemans** [comment]
With #21 merged this issue is also fixed. You can now customize the owner and group using the `sudo_sudoersd_owner` and `sudo_sudoersd_group` variables. (Thanks again @memoryleak! )

**Comment by groggemans** [comment]
I've just released a new version of the role on Ansible Galaxy as well (v1.5.0).
