### ISSUE TITLE
Deprecated with_flattened failing ansible-lint tests

### ISSUE THREAD

**Issue by reinamora137** [GROG/ansible-role-sudo#22]
with_flattened:
    - "{{ sudo_grouplist }}"
    - "{{ sudo_grouplist_group }}"
    - "{{ sudo_grouplist_host }}"
    
 to: 

loop:  "{{ sudo_grouplist + sudo_grouplist_group + sudo_grouplist_host }}"

**Comment by groggemans** [comment]
Hi @moonblink 

Thank you for this report!

This issue is currently not high on the priority list and it might take some time to get this fixed across all GROG roles.
Feel free to open a PR if you require a more urgent fix!

Kind regards
Gertjan
