### ISSUE TITLE
Dependency on GROG.package could use an update

### ISSUE THREAD

**Issue by stejoo** [GROG/ansible-role-sudo#24]
The dependency on GROG.package refers to an older version. Not a direct issue but the specific version requested is `v1.2.4`: as stated in https://github.com/GROG/ansible-role-sudo/blob/master/meta/requirements.yml#L2

While functional this causes Ansible to produce deprecation warnings for the used `include:` statements in there. A fix is available from v1.3.0 forward. Current version is: https://github.com/GROG/ansible-role-package/releases/tag/v1.3.1

May the dependency be updated to v1.3.1 to alleviate the deprecations warnings?

**Comment by groggemans** [comment]
Thank you for the report and PR!
