### ISSUE TITLE
sudoers.d files included twice on Debian 12 (and others?)

### ISSUE THREAD

**Issue by stejoo** [GROG/ansible-role-sudo#31]
Running this role against current Debian (bookworm) results in `/etc/sudoers.d` being included twice.

To a user running `sudo -l` this looks like:
```
User myname@mydomain.example may run the following commands on myhost:
    (ALL) ALL
    (ALL) ALL
```

The cause of this is this bit at the end of the `/etc/sudoers`  file:

```
# See sudoers(5) for more information on "@include" directives:

@includedir /etc/sudoers.d
#includedir /etc/sudoers.d
```

Both these statements are valid "include" statements. As such sudo seems to apply statements in files within `/etc/sudoers.d/` twice. While this does not break `sudo` behaviour to my current knowledge, it does look funny!

The `@`-style was added, fairly recently, to sudo in version 1.9.1 (2020-06-19). While many distros already ship a recent enough version there are still supported distros, such as RHEL8, that ship with an older version of sudo. For compatibility with sudo versions prior to 1.9.1, `#include` and `#includedir` are still supported today. To resolve this issue I suggest improving the `regexp` statement of the `Enable sudoers.d` task, on line 28 of `tasks/main.yml`:
https://github.com/GROG/ansible-role-sudo/blob/125707b3ef669f0a173888b80b3e0477025d1abc/tasks/main.yml#L28
to also match `@include` lines.

**Comment by chrisvanmeer** [comment]
Experienced this on Ubuntu Jammy as well when I was working with CmdAlias which failed because it was read twice.

**Comment by stejoo** [comment]
Ah. So it can make sudo fail. I'll try to whip up a fix and PR. :smile:
