### ISSUE TITLE
Permission of `/etc/sudoers` file

### ISSUE THREAD

**Issue by stejoo** [GROG/ansible-role-sudo#33]
In commit 125707b3ef669f0a173888b80b3e0477025d1abc the mode of `/etc/sudoers.d` was defined as:
https://github.com/GROG/ansible-role-sudo/blob/125707b3ef669f0a173888b80b3e0477025d1abc/tasks/main.yml#L29

I am curious why this mode was chosen in particular. In both Debian and Red Hat the default mode of the `/etc/sudoers.d` directory is set to `'0440`'. I can imagine this is different for other distributions and this mode works. It's an extra "change" I noticed in my Ansible runs and that made me curious.

**Comment by groggemans** [comment]
I think there are two issues.. The line you referenced is the `"0750"` permissions for the sudoers file, and the one you are describing is the `"0750"` for the sudoers.d directory!

And I agree that both need to be fixed. I don't think they result in any security issues, but all distros I could imediatly check seem to default to `"0440"`.

Would you like to create a PR yourself?

**Comment by stejoo** [comment]
Ah, yeah. I was a bit in a hurry to finish up and shutdown my laptop for the day. You are correct about the file, that's the one I meant. I think my mind went to the directory because the task is about the include of that directory. I'll have a careful look at the change when I recreate the occurrence on a clean machine. 
Glad you agree to sticking to what the distro ships with. 

I will a careful look at the permissions of file and directory on a couple of clean machines and make a PR for it coming Monday or Tuesday. :smile:

**Comment by stejoo** [comment]
The `/etc/sudoers.d` directory was indeed fine. Only the permissions of the `/etc/sudoers` config file we're set different from what is typically shipped. Made PR to resolve the issue.

If you would be willing to tag a new version/release afterward I would be grateful. :smile:

**Comment by groggemans** [comment]
Looks like I was confused about the directory also requiring changes.. :confused:  Indeed only the sudoers file needed to be fixed.

I've released it as a new minor release given the support for the new `@include` syntax. And should be available on Galaxy as well.

Big thank you for the contributions!
