### ISSUE TITLE
More complex sudoers file

### ISSUE THREAD

**Issue by mikerj1** [GROG/ansible-role-sudo#8]
Hi GROG - thanks for sharing your work!  It doesn't appear that a more complex sudoers file is possible, but asking for confirmation.  An example of what I would like to be able to do:

testuser ALL=(root) NOPASSWD: /bin/ls,/bin/grep,/etc/init.d/nginx
testuser ALL=(nginx) NOPASSWD: ALL

Thanks!

**Comment by groggemans** [comment]
Thank you for your interest in this role!

At the moment this isn't possible. It's a fairly common use case tho, so I'll try to support it.

If it doesn't require big changes I should be able to add it this week.

**Comment by mikerj1** [comment]
Thanks for the response and again for the contribution.

**Comment by mikerj1** [comment]
Worked perfectly - thanks!
